### ISSUE TITLE
Extension causes high cpu load

### ISSUE THREAD

**Issue by robturtle** [Bajdzis/vscode-database#100]
- Issue Type: `Performance`
- Extension Name: `vscode-database`
- Extension Version: `2.1.5`
- OS Version: `Darwin x64 16.7.0`
- VSCode version: `1.33.1`

[~/bajdzis.vscode-database-unresponsive.cpuprofile.txt](https://gist.github.com/robturtle/7a2cef0450d742d952baae3d161bab30)

**Comment by EPMatt** [comment]
@robturtle it looks like you're running queries with one of the commands which generate a Markdown preview. What happens if you execute the same query/script with **Run File as query with CSV result** or **Run selected text as SQL query with CSV result**?  
Does it cause a sharp increase in CPU usage?
